# Generated by Django 3.1 on 2020-08-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('departure_city', models.CharField(max_length=128)),
                ('arrival_city', models.CharField(max_length=128)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('stay_duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('departure_city', models.CharField(max_length=128)),
                ('arrival_city', models.CharField(max_length=128)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_search.searchquery')),
            ],
        ),
    ]
