# Generated by Django 3.1 on 2020-08-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchquery',
            old_name='created_date',
            new_name='date_created',
        ),
    ]
